title:            Braving the Backlog
description:      Defeating the Backlog Beast, one game at a time

# put your disqus here
disqus_shortname: braving-the-backlog
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://bravingthebacklog.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'About'
    url: '/about'
    type: 'about'
#  - title: 'Favorites'
#    url: '#'
#    submenu:
#      - title: 'Code Highlighter'
#        url: '/intro/code-highlighting-post/'
#      - title: 'Sample Post'
#        url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           "Braving the Backlog"
  site:           
  avatar:         
  bio:            ""
  email:          
  # Twitter nick for use in Twitter cards and follow button.
  twitter: bravingbacklog 
  # GitHub nick for use in follow button in author block.
  github: 
  # patreon: bravingthebacklog

authors:
  bsinky:
    name: Ben
    display_name: bsinky
    avatar: images/bsinky.png
    site: /about
    bio:            "The self-proclaimed \"Guy with the Backlog\", as of this writing his Steam backlog is slowly growing to the point of consuming him. Meanwhile, he spends most of his time trying to catch up on the retro classics he missed, as well as replaying the games he grew up with."
    social:
      - title: "reddit"
        url: "https://reddit.com/user/bsinky"
      - title: "github"
        url: "https://github.com/bsinky"
      - title: "steam"
        url: "https://steamcommunity.com/id/bsinky"
      - title: "list" # really "howlongtobeat" but no FontAwesome icon for that
        url: "https://howlongtobeat.com/user.php?n=bsinky"
  patronuslight:
    name: Shannon
    display_name: PatronusLight
    avatar: images/patronuslight.png
    site: /about
    bio: "She enjoys playing The Sims, and has logged hundreds of hours into The Sims 4! Skyrim is another game in which Shannon is equally well-versed, as is Persona 5. She also really likes The Bard's Tale and Harry Potter games on the PS2."
    social:

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: bravingbacklog

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "reddit"
    url: "https://reddit.com/user/bsinky"
  - title: "github"
    url: "https://github.com/bsinky"
  - title: "steam"
    url: "https://steamcommunity.com/id/bsinky"
  - title: "list" # really "howlongtobeat" but no FontAwesome icon for that
    url: "https://howlongtobeat.com/user.php?n=bsinky"

# Background image to be tiled on all pages
background: bg.jpg

# Analytics and webmaster tools stuff goes here
google_analytics: UA-101240207-2
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: false

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
plugins: [jekyll-paginate,jekyll-redirect-from]
# theme: neo-hpstr-jekyll-theme

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: bsinky
